# Generated by Django 5.1.7 on 2025-03-27 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postattachment_alter_post_options_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='image',
            field=models.ImageField(default=123, upload_to='image', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postattachment',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='Название картинки'),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='post',
            field=models.ForeignKey(default=-2001, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
    ]
